name: Deploy to GitHub Pages

on:
  push:
    branches: main

env:
  DOMAIN: arl.sh

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install dependencies
      run: |
        npm install

    - name: Build project
      run: |
        ./node_modules/.bin/gatsby build

    - name: Define custom domain
      run: |
        echo "$DOMAIN" > ./public/CNAME

    - name: Login to GitHub
      run: |
        git remote set-url origin "https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to gh-pages
      run: |
        ./node_modules/.bin/gh-pages -d public -u "github-actions <41898282+github-actions@users.noreply.github.com>"
